
aliyun:
  oss:
    accessKeyId: ${OSS_ACCESS_KEY_ID}
    accessKeySecret: ${OSS_ACCESS_KEY_SECRET}
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    bucketName: show-tails
spring:
  servlet:
    multipart:
      max-file-size: 10MB # 单个文件最大大小，可按需调整
      max-request-size: 100MB # 整个请求的最大大小，可按需调整