---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by aex.
--- DateTime: 2025/11/14 13:35
---
--- 优惠卷id
local voucherId = ARGV[1]
--- 用户id
local userId = ARGV[2]
--- 订单id
local orderId = ARGV[3]
--- 库存key
local stockKey = "seckill:stock:" .. voucherId
--- 订单key
local orderKey = "seckill:order:" .. voucherId
if tonumber(redis.call('get', stockKey)) < 1 then
    return 1
end
if redis.call('sismember', orderKey, userId) == 1 then
    return 2
end
redis.call('decrby', stockKey,1)
redis.call('sadd', orderKey, userId)
redis.call('xadd','stream.orders', '*', 'userId', userId, 'voucherId', voucherId, 'id', orderId)
return 0
