---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by aex.
--- DateTime: 2025/11/9 17:57
---

if redis.call('get', KEYS[1]) == ARGV[1] then
    return redis.call('del', KEYS[1])
    else
    return 0
end

